export default [
    {
        "_id": "Q001",
        "title": "Rocket Propulsion Fundamentals",
        "description": "<p>Test your understanding of basic rocket propulsion concepts including thrust, specific impulse, and engine types.</p>",
        "courseCode": "RS101",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": "after_due_date",
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "totalPoints": 30,
        "published": true,
        "availableDate": "2024-01-15T00:00:00.000Z",
        "dueDate": "2024-01-22T23:59:59.000Z",
        "untilDate": "2024-01-25T23:59:59.000Z"
    },
    {
        "_id": "Q002",
        "title": "Aerodynamics Midterm",
        "description": "<p>Comprehensive assessment covering fluid dynamics, lift and drag forces, and airfoil design principles.</p>",
        "courseCode": "RS102",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Exams",
        "shuffleAnswers": true,
        "timeLimit": 45,
        "multipleAttempts": false,
        "showCorrectAnswers": "never",
        "accessCode": "AERO2024",
        "oneQuestionAtATime": true,
        "webcamRequired": true,
        "lockQuestionsAfterAnswering": true,
        "totalPoints": 50,
        "published": true,
        "availableDate": "2024-02-10T00:00:00.000Z",
        "dueDate": "2024-02-17T23:59:59.000Z",
        "untilDate": "2024-02-17T23:59:59.000Z"
    },
    {
        "_id": "Q003",
        "title": "Spacecraft Systems Practice Quiz",
        "description": "<p>Practice quiz on spacecraft structure, propulsion, and thermal control systems. Unlimited attempts allowed!</p>",
        "courseCode": "RS103",
        "quizType": "Practice Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 15,
        "multipleAttempts": true,
        "showCorrectAnswers": "immediately",
        "accessCode": "",
        "oneQuestionAtATime": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "totalPoints": 20,
        "published": true,
        "availableDate": "2024-01-20T00:00:00.000Z",
        "dueDate": "2024-03-15T23:59:59.000Z",
        "untilDate": "2024-03-20T23:59:59.000Z"
    },
    {
        "_id": "Q004",
        "title": "Organic Chemistry Mechanisms",
        "description": "<p>Quiz on reaction mechanisms, functional groups, and organic synthesis techniques.</p>",
        "courseCode": "RS104",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 30,
        "multipleAttempts": true,
        "showCorrectAnswers": "after_due_date",
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "totalPoints": 40,
        "published": true,
        "availableDate": "2024-02-01T00:00:00.000Z",
        "dueDate": "2024-02-08T23:59:59.000Z",
        "untilDate": "2024-02-10T23:59:59.000Z"
    },
    {
        "_id": "Q005",
        "title": "Coordination Chemistry Survey",
        "description": "<p>Survey about your understanding and interest in coordination chemistry topics.</p>",
        "courseCode": "RS105",
        "quizType": "Ungraded Survey",
        "assignmentGroup": "Assignments",
        "shuffleAnswers": false,
        "timeLimit": 10,
        "multipleAttempts": false,
        "showCorrectAnswers": "immediately",
        "accessCode": "",
        "oneQuestionAtATime": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "totalPoints": 0,
        "published": true,
        "availableDate": "2024-01-10T00:00:00.000Z",
        "dueDate": "2024-01-17T23:59:59.000Z",
        "untilDate": "2024-01-20T23:59:59.000Z"
    },
    {
        "_id": "Q006",
        "title": "Thermodynamics and Kinetics",
        "description": "<p>Graded assessment on thermodynamic principles, reaction kinetics, and equilibrium concepts.</p>",
        "courseCode": "RS106",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 25,
        "multipleAttempts": false,
        "showCorrectAnswers": "after_due_date",
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "totalPoints": 35,
        "published": true,
        "availableDate": "2024-02-15T00:00:00.000Z",
        "dueDate": "2024-02-22T23:59:59.000Z",
        "untilDate": "2024-02-25T23:59:59.000Z"
    },
    {
        "_id": "Q007",
        "title": "Elvish Language Basics",
        "description": "<p>Introduction to Sindarin and Quenya: Test your knowledge of basic vocabulary and grammar.</p>",
        "courseCode": "RS107",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": true,
        "showCorrectAnswers": "immediately",
        "accessCode": "",
        "oneQuestionAtATime": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "totalPoints": 25,
        "published": true,
        "availableDate": "2024-01-12T00:00:00.000Z",
        "dueDate": "2024-01-19T23:59:59.000Z",
        "untilDate": "2024-01-22T23:59:59.000Z"
    },
    {
        "_id": "Q008",
        "title": "Council of Elrond Case Study",
        "description": "<p>Analyze the diplomatic strategies and decisions made during the Council of Elrond.</p>",
        "courseCode": "RS108",
        "quizType": "Graded Survey",
        "assignmentGroup": "Project",
        "shuffleAnswers": false,
        "timeLimit": 40,
        "multipleAttempts": false,
        "showCorrectAnswers": "never",
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "totalPoints": 45,
        "published": true,
        "availableDate": "2024-02-05T00:00:00.000Z",
        "dueDate": "2024-02-12T23:59:59.000Z",
        "untilDate": "2024-02-15T23:59:59.000Z"
    },
    {
        "_id": "Q009",
        "title": "Propulsion Final Exam",
        "description": "<p>Comprehensive final examination covering all topics in rocket propulsion.</p>",
        "courseCode": "RS101",
        "quizType": "Graded Quiz",
        "assignmentGroup": "Exams",
        "shuffleAnswers": true,
        "timeLimit": 60,
        "multipleAttempts": false,
        "showCorrectAnswers": "never",
        "accessCode": "FINAL2024",
        "oneQuestionAtATime": true,
        "webcamRequired": true,
        "lockQuestionsAfterAnswering": true,
        "totalPoints": 100,
        "published": false,
        "availableDate": "2024-05-10T00:00:00.000Z",
        "dueDate": "2024-05-17T23:59:59.000Z",
        "untilDate": "2024-05-17T23:59:59.000Z"
    },
    {
        "_id": "Q010",
        "title": "Spacecraft Design Concepts",
        "description": "<p>Quick check on basic spacecraft design principles and terminology.</p>",
        "courseCode": "RS103",
        "quizType": "Practice Quiz",
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 10,
        "multipleAttempts": true,
        "showCorrectAnswers": "immediately",
        "accessCode": "",
        "oneQuestionAtATime": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "totalPoints": 15,
        "published": true,
        "availableDate": "2024-01-08T00:00:00.000Z",
        "dueDate": "2024-05-15T23:59:59.000Z",
        "untilDate": "2024-05-20T23:59:59.000Z"
    }
];
